version: '3.1'
services:
  identification:
    image: mf2c/identification:latest
    container_name: identification
    volumes:
     - mydata:/data
    ports:
     - 46060:46060
    environment:
     # assign to the IDKey variable the correct value given the user email
     # IDKey sould be unique for every user
volumes:
  mydata: {}
