version: '3.1'
services:
  identification:
    image: mf2c/identification:latest
    container_name: identification
    volumes:
     - mydata:/data
    ports:
     - 46060:46060
    environment:
      - mF2C_User=${usr} 
      - mF2C_Pass=${pwd}
volumes:
  mydata: {}
